// Downloads the site photos in scripts/photos.json from Wikimedia Commons.
// Writes local copies to public/assets/places/<place>/ and the credits to src/data/photos.ts.
// Usage: node scripts/fetch-photos.mjs
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const WIDTH = 1280
const UA = 'biblical-maps/0.1 (https://github.com/ajbertra91/biblical-maps)'
const manifest = JSON.parse(readFileSync('scripts/photos.json', 'utf8'))
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'", nbsp: ' ' }
const plain = (html = '') => html.replace(/<[^>]*>/g, '').replace(/&(\w+|#\d+);/g, (e, n) => ENTITIES[n] ?? e).replace(/\s+/g, ' ').trim()

async function get(url) {
  for (let i = 0; i < 4; i++) {
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    if (res.ok) return res
    // Commons limits the request rate. Wait and try again.
    await sleep(2000 * (i + 1))
  }
  throw new Error(`GET ${url} failed`)
}

async function info(file) {
  const q = new URLSearchParams({
    action: 'query', format: 'json', titles: `File:${file}`, prop: 'imageinfo',
    iiprop: 'url|extmetadata', iiurlwidth: String(WIDTH),
  })
  const d = await (await get(`https://commons.wikimedia.org/w/api.php?${q}`)).json()
  const page = Object.values(d.query.pages)[0]
  if (!page.imageinfo) throw new Error(`No file on Commons: ${file}`)
  const ii = page.imageinfo[0]
  const m = ii.extmetadata
  return {
    // The API gives the original when it is narrower than WIDTH.
    url: ii.thumburl ?? ii.url,
    credit: plain(m.Artist?.value) || plain(m.Credit?.value) || 'Unknown',
    license: m.LicenseShortName?.value ?? 'See source',
    licenseUrl: m.LicenseUrl?.value,
    source: ii.descriptionurl,
  }
}

const out = {}
for (const [place, photos] of Object.entries(manifest)) {
  mkdirSync(`public/assets/places/${place}`, { recursive: true })
  out[place] = []
  for (const [i, p] of photos.entries()) {
    const meta = await info(p.file)
    const name = `${i + 1}.jpg`
    const buf = Buffer.from(await (await get(meta.url)).arrayBuffer())
    writeFileSync(`public/assets/places/${place}/${name}`, buf)
    const { url: _url, ...credit } = meta
    out[place].push({ src: `assets/places/${place}/${name}`, caption: p.caption, ...credit })
    console.log(place, name, `${Math.round(buf.length / 1024)} KB`, credit.license, '·', credit.credit)
    await sleep(500)
  }
}

const ts = `// Generated by scripts/fetch-photos.mjs. Do not edit. Change scripts/photos.json instead.
// Each photo is a local copy of a file on Wikimedia Commons. Its license requires the credit line.

export interface Photo {
  /** Path under the site base URL. */
  src: string
  caption: string
  credit: string
  license: string
  licenseUrl?: string
  /** The file page on Wikimedia Commons. */
  source: string
}

export const PHOTOS: Record<string, Photo[]> = ${JSON.stringify(out, null, 2)}
`
writeFileSync('src/data/photos.ts', ts)
