// Generated by scripts/fetch-photos.mjs. Do not edit. Change scripts/photos.json instead.
// Each photo is a local copy of a file on Wikimedia Commons. Its license requires the credit line.

export interface Photo {
  /** Path under the site base URL. */
  src: string
  caption: string
  credit: string
  license: string
  licenseUrl?: string
  /** The file page on Wikimedia Commons. */
  source: string
}

export const PHOTOS: Record<string, Photo[]> = {
  "ur": [
    {
      "src": "assets/places/ur/1.jpg",
      "caption": "The ziggurat of Ur. It dates from about 2100 BC. Its front was restored in the 1980s.",
      "credit": "Alli Khalil",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Ziggurat_of_Ur_Site_in_Nasiriyah_01.jpg"
    },
    {
      "src": "assets/places/ur/2.jpg",
      "caption": "Excavated houses at Ur, with the ziggurat behind them.",
      "credit": "M.Lubinski from Iraq,USA.",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "source": "https://commons.wikimedia.org/wiki/File:Ur-Nassiriyah.jpg"
    },
    {
      "src": "assets/places/ur/3.jpg",
      "caption": "The ruins of Ur, with the ziggurat in the distance.",
      "credit": "Alli Khalil",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Ziggurat_of_Ur_Site_in_Nasiriyah_03.jpg"
    }
  ],
  "haran": [
    {
      "src": "assets/places/haran/1.jpg",
      "caption": "Beehive houses of mud brick at Harran.",
      "credit": "Zhengan",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Harran_beehive_houses_(2).JPG"
    },
    {
      "src": "assets/places/haran/2.jpg",
      "caption": "Ruins at Harran. The tower is the minaret of the Great Mosque.",
      "credit": "Buda2000",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Harran_(3).jpg"
    },
    {
      "src": "assets/places/haran/3.jpg",
      "caption": "Harran and the plain around it.",
      "credit": "Hamdigumus",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "source": "https://commons.wikimedia.org/wiki/File:Harran_2015.jpg"
    }
  ],
  "shechem": [
    {
      "src": "assets/places/shechem/1.jpg",
      "caption": "Tell Balata, the site of ancient Shechem, in the city of Nablus.",
      "credit": "יאיר דב",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%D7%A9%D7%9B%D7%9D_%D7%94%D7%A2%D7%AA%D7%99%D7%A7%D7%94.jpg"
    },
    {
      "src": "assets/places/shechem/2.jpg",
      "caption": "Stone walls at Tell Balata.",
      "credit": "TrickyH",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Tell_Balata.jpg"
    },
    {
      "src": "assets/places/shechem/3.jpg",
      "caption": "Nablus fills the valley around ancient Shechem.",
      "credit": "עדירל",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:TelShchem5628.JPG"
    }
  ],
  "bethel": [
    {
      "src": "assets/places/bethel/1.jpg",
      "caption": "Fields at Beitin, the traditional site of Bethel.",
      "credit": "Bukvoed",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Beitin-2246.jpg"
    },
    {
      "src": "assets/places/bethel/2.jpg",
      "caption": "Bethel from the south, in an old photograph.",
      "credit": "OSU Special Collections & Archives : Commons",
      "license": "No restrictions",
      "licenseUrl": "https://www.flickr.com/commons/usage/",
      "source": "https://commons.wikimedia.org/wiki/File:Bethel_from_the_South_(4879201735).jpg"
    },
    {
      "src": "assets/places/bethel/3.jpg",
      "caption": "The road into Beitin.",
      "credit": "Bukvoed",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Beitin-2221.jpg"
    }
  ],
  "mamre": [
    {
      "src": "assets/places/mamre/1.jpg",
      "caption": "Excavations at Ramat el-Khalil, the traditional site of Mamre, in an early photograph.",
      "credit": "Matson Collection",
      "license": "Public domain",
      "source": "https://commons.wikimedia.org/wiki/File:Southern_Palestine,_Hebron,_Beersheba_and_Gaza_area._Ramet_el-Khalil,_Mamre_excavations._Gen._25-9_LOC_matpc.22876.jpg"
    },
    {
      "src": "assets/places/mamre/2.jpg",
      "caption": "The Oak of Abraham in Hebron. Some traditions put the oaks of Mamre here.",
      "credit": "Copper Kettle",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "source": "https://commons.wikimedia.org/wiki/File:Oak_of_Mamre_1.jpg"
    },
    {
      "src": "assets/places/mamre/3.jpg",
      "caption": "The Russian convent at the Oak of Abraham, in an early photograph.",
      "credit": "Matson Collection",
      "license": "Public domain",
      "source": "https://commons.wikimedia.org/wiki/File:Convent_at_Mamre_near_Hebron_(Abraham%27s_Oak)_LOC_matpc.21820.jpg"
    }
  ],
  "machpelah": [
    {
      "src": "assets/places/machpelah/1.jpg",
      "caption": "The building over the Cave of the Patriarchs in Hebron. Herod the Great built its walls.",
      "credit": "Utilisateur:Djampa - User:Djampa",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Hebron_Cave_of_the_Patriarchs.jpg"
    },
    {
      "src": "assets/places/machpelah/2.jpg",
      "caption": "The cenotaph of Abraham inside the building.",
      "credit": "Randa107",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%D9%85%D9%82%D8%A7%D9%85_%D8%B3%D9%8A%D8%AF%D9%86%D8%A7_%D8%A5%D8%A8%D8%B1%D8%A7%D9%87%D9%8A%D9%85_%D8%B9%D9%84%D9%8A%D9%87_%D8%A7%D9%84%D8%B3%D9%84%D8%A7%D9%85.jpg"
    },
    {
      "src": "assets/places/machpelah/3.jpg",
      "caption": "The old city of Hebron, with the Cave of the Patriarchs at the back.",
      "credit": "Baraa Zm",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:HEBRON_OLD_CITY_0001.jpg"
    }
  ],
  "siddim": [
    {
      "src": "assets/places/siddim/1.jpg",
      "caption": "Salt on the shore of the Dead Sea, near Neve Zohar at the south end. Genesis calls it the Salt Sea.",
      "credit": "Tiia Monto",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Dead_Sea_shore.jpg"
    },
    {
      "src": "assets/places/siddim/2.jpg",
      "caption": "The gate of Bab edh-Dhra, above the south end of the Dead Sea.",
      "credit": "Deg777",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Bab_edh-Dhra_gate_overlooking_south_end_dead_sea_2014.jpg"
    },
    {
      "src": "assets/places/siddim/3.jpg",
      "caption": "Rock salt at Mount Sodom, by the south end of the Dead Sea.",
      "credit": "Shayshal2",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Mount_Sodom.jpg"
    }
  ],
  "dan": [
    {
      "src": "assets/places/dan/1.jpg",
      "caption": "The mud-brick city gate at Tel Dan, from about 1750 BC. People call it Abraham's Gate.",
      "credit": "Lajoya02",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Abraham%27s_Gate.jpg"
    },
    {
      "src": "assets/places/dan/2.jpg",
      "caption": "The stone gate at Tel Dan, from the time of the kings of Israel.",
      "credit": "Fallaner",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Holy_Land_2022_(1)_P633_Tel_Dan_gate.jpg"
    },
    {
      "src": "assets/places/dan/3.jpg",
      "caption": "A spring pool at Tel Dan. These springs feed the Jordan River.",
      "credit": "שאולה haitner",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
      "source": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_78810_the_pool_at_tel_dan.jpg"
    }
  ],
  "salem": [
    {
      "src": "assets/places/salem/1.jpg",
      "caption": "The City of David from the air. It is the ridge south of the Temple Mount.",
      "credit": "AVRAM GRAICER",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Aerial_view_Temple_Mount_Silwan_Kidron_Valley_City_of_David.jpeg"
    },
    {
      "src": "assets/places/salem/2.jpg",
      "caption": "Canaanite and Israelite walls on the east slope of the City of David.",
      "credit": "Ian Scott",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "source": "https://commons.wikimedia.org/wiki/File:Canaanite_and_Israelite_walls_on_Jerusalem%27s_eastern_hill_(6388970869).jpg"
    },
    {
      "src": "assets/places/salem/3.jpg",
      "caption": "The Temple Mount and the City of David, in an early aerial photograph.",
      "credit": "Matson Collection",
      "license": "Public domain",
      "source": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Temple_Mount_and_City_of_David.JPG"
    }
  ],
  "moriah": [
    {
      "src": "assets/places/moriah/1.jpg",
      "caption": "The Temple Mount from the air, from the south.",
      "credit": "Godot13",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Jerusalem-2013(2)-Aerial-Temple_Mount-(south_exposure).jpg"
    },
    {
      "src": "assets/places/moriah/2.jpg",
      "caption": "The Dome of the Rock on the Temple Mount. The Mount of Olives is behind it.",
      "credit": "arikb",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/wiki/File:HarHabait.JPG"
    }
  ],
  "gerar": [
    {
      "src": "assets/places/gerar/1.jpg",
      "caption": "Tel Haror, one proposed site of Gerar.",
      "credit": "Aaadir",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "source": "https://commons.wikimedia.org/wiki/File:%D7%AA%D7%9C_%D7%94%D7%A8%D7%95%D7%A81.jpg"
    },
    {
      "src": "assets/places/gerar/2.jpg",
      "caption": "The view from Tel Haror over the western Negev.",
      "credit": "Aaadir",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "source": "https://commons.wikimedia.org/wiki/File:%D7%AA%D7%9C_%D7%94%D7%A8%D7%95%D7%A8_%D7%A0%D7%95%D7%A3.jpg"
    }
  ],
  "beersheba": [
    {
      "src": "assets/places/beersheba/1.jpg",
      "caption": "Tel Be'er Sheva from the air at sunset.",
      "credit": "זאב שטיין",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
      "source": "https://commons.wikimedia.org/wiki/File:104264_tel_beer_sheva_PikiWiki_Israel.jpg"
    },
    {
      "src": "assets/places/beersheba/2.jpg",
      "caption": "A well and a trough at Tel Be'er Sheva.",
      "credit": "Dr. Avishai Teicher",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
      "source": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_33680_Well_and_trough_in_Tel_Beer_Sheva.JPG"
    },
    {
      "src": "assets/places/beersheba/3.jpg",
      "caption": "The excavated Israelite city at Tel Be'er Sheva.",
      "credit": "gugganij",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Tel_Be%27er_Sheva_Overview_2007041.JPG"
    }
  ]
}
